# Assignment_9_CCTV_Object_Detection

Apply object detection from CCTV footage.

## Aim
Apply object detection to CCTV footage using YOLO.

**Input:** your own `.mp4`, `.avi`, or `.mov` CCTV/video file.

**Output:** annotated video with detected objects.

The result ZIP contains the processed video and a detection summary.

In [ ]:
# Install only the object-detection package. Do not upgrade NumPy/Pandas.
!pip -q install ultralytics --no-deps

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.9/46.9 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 20.2 MB/s eta 0:00:00

In [ ]:
from google.colab import files
import os, shutil, json
from collections import Counter

uploaded = files.upload()
VIDEO_PATH = next(iter(uploaded.keys()))
RESULT_DIR = "/content/results"
os.makedirs(RESULT_DIR, exist_ok=True)
print("Video:", VIDEO_PATH)

Saving WhatsApp Video 2026-10-06 at 00.27.03.mp4 to WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4
Video: WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4

In [ ]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.predict(
    source=VIDEO_PATH,
    save=True,
    project="/content",
    name="cctv_detected",
    conf=0.35,
    verbose=True
)

OUTPUT_DIR="/content/cctv_detected"
print("Processed output folder:", OUTPUT_DIR)

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 59.0MB/s 0.1s

WARNING ⚠️
Inference results will accumulate in RAM unless `stream=True` is passed, which can cause out-of-memory errors for large
sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 persons, 4 cars, 461.8ms
video 1/1 (frame 2/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 148.4ms
video 1/1 (frame 3/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 118.5ms
video 1/1 (frame 4/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 114.8ms
video 1/1 (frame 5/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 108.4ms
video 1/1 (frame 6/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 108.6ms
video 1/1 (frame 7/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 2 cars, 109.6ms
video 1/1 (frame 8/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 133.9ms
video 1/1 (frame 9/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 133.9ms
video 1/1 (frame 10/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 113.3ms
video 1/1 (frame 11/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 9 cars, 118.4ms
video 1/1 (frame 12/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 113.0ms
video 1/1 (frame 13/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 114.0ms
video 1/1 (frame 14/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 132.5ms
video 1/1 (frame 15/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 7 cars, 112.2ms
video 1/1 (frame 16/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 124.4ms
video 1/1 (frame 17/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 112.9ms
video 1/1 (frame 18/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 123.7ms
video 1/1 (frame 19/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 119.0ms
video 1/1 (frame 20/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 bus, 116.7ms
video 1/1 (frame 21/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 1 bus, 119.0ms
video 1/1 (frame 22/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 114.4ms
video 1/1 (frame 23/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 1 bus, 126.1ms
video 1/1 (frame 24/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 119.8ms
video 1/1 (frame 25/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 bus, 150.9ms
video 1/1 (frame 26/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 1 bus, 186.9ms
video 1/1 (frame 27/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 216.3ms
video 1/1 (frame 28/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 200.6ms
video 1/1 (frame 29/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 1 bus, 198.5ms
video 1/1 (frame 30/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 1 truck, 194.6ms
video 1/1 (frame 31/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 1 bus, 195.8ms
video 1/1 (frame 32/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 bus, 187.8ms
video 1/1 (frame 33/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 5 cars, 1 bus, 195.6ms
video 1/1 (frame 34/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 4 cars, 1 bus, 192.4ms
video 1/1 (frame 35/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 5 cars, 1 bus, 190.3ms
video 1/1 (frame 36/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 198.0ms
video 1/1 (frame 37/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 1 car, 1 train, 203.0ms
video 1/1 (frame 38/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 4 cars, 194.4ms
video 1/1 (frame 39/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 1 car, 190.9ms
video 1/1 (frame 40/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 1 bus, 181.6ms
video 1/1 (frame 41/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 bus, 120.2ms
video 1/1 (frame 42/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 bus, 115.4ms
video 1/1 (frame 43/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 bus, 113.7ms
video 1/1 (frame 44/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 9 cars, 1 bus, 119.5ms
video 1/1 (frame 45/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 1 bus, 133.3ms
video 1/1 (frame 46/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 bus, 119.6ms
video 1/1 (frame 47/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 1 bus, 117.4ms
video 1/1 (frame 48/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 112.1ms
video 1/1 (frame 49/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 112.0ms
video 1/1 (frame 50/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 113.4ms
video 1/1 (frame 51/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 4 cars, 115.4ms
video 1/1 (frame 52/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 119.5ms
video 1/1 (frame 53/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 117.6ms
video 1/1 (frame 54/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 114.9ms
video 1/1 (frame 55/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 10 cars, 114.4ms
video 1/1 (frame 56/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 12 cars, 115.0ms
video 1/1 (frame 57/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 114.4ms
video 1/1 (frame 58/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 12 cars, 122.3ms
video 1/1 (frame 59/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 10 cars, 122.9ms
video 1/1 (frame 60/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 11 cars, 126.7ms
video 1/1 (frame 61/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 12 cars, 113.0ms
video 1/1 (frame 62/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 112.9ms
video 1/1 (frame 63/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 10 cars, 112.6ms
video 1/1 (frame 64/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 115.8ms
video 1/1 (frame 65/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 111.6ms
video 1/1 (frame 66/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 117.1ms
video 1/1 (frame 67/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 114.7ms
video 1/1 (frame 68/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 129.9ms
video 1/1 (frame 69/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 108.9ms
video 1/1 (frame 70/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 115.1ms
video 1/1 (frame 71/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 115.9ms
video 1/1 (frame 72/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 truck, 111.5ms
video 1/1 (frame 73/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 119.2ms
video 1/1 (frame 74/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 car, 117.2ms
video 1/1 (frame 75/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 122.8ms
video 1/1 (frame 76/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 118.2ms
video 1/1 (frame 77/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 114.3ms
video 1/1 (frame 78/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 116.0ms
video 1/1 (frame 79/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 car, 116.4ms
video 1/1 (frame 80/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 truck, 112.9ms
video 1/1 (frame 81/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 truck, 118.0ms
video 1/1 (frame 82/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 bus, 1 truck, 115.2ms
video 1/1 (frame 83/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 bus, 1 truck, 127.5ms
video 1/1 (frame 84/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 116.8ms
video 1/1 (frame 85/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 112.6ms
video 1/1 (frame 86/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 6 cars, 118.6ms
video 1/1 (frame 87/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 114.2ms
video 1/1 (frame 88/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 113.1ms
video 1/1 (frame 89/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 121.5ms
video 1/1 (frame 90/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 1 truck, 118.4ms
video 1/1 (frame 91/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 1 truck, 128.3ms
video 1/1 (frame 92/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 1 truck, 112.7ms
video 1/1 (frame 93/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 truck, 112.0ms
video 1/1 (frame 94/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 119.7ms
video 1/1 (frame 95/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 8 cars, 1 bus, 111.7ms
video 1/1 (frame 96/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 1 truck, 116.6ms
video 1/1 (frame 97/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 12 cars, 114.0ms
video 1/1 (frame 98/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 112.6ms
video 1/1 (frame 99/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 9 cars, 1 truck, 119.5ms
video 1/1 (frame 100/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 10 cars, 113.7ms
video 1/1 (frame 101/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 10 cars, 115.1ms
video 1/1 (frame 102/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 10 cars, 115.3ms
video 1/1 (frame 103/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 10 cars, 114.7ms
video 1/1 (frame 104/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 9 cars, 117.2ms
video 1/1 (frame 105/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 115.1ms
video 1/1 (frame 106/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 7 cars, 128.6ms
video 1/1 (frame 107/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 114.0ms
video 1/1 (frame 108/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 1 truck, 113.6ms
video 1/1 (frame 109/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 117.3ms
video 1/1 (frame 110/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 117.2ms
video 1/1 (frame 111/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 1 truck, 117.7ms
video 1/1 (frame 112/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 115.7ms
video 1/1 (frame 113/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 truck, 111.7ms
video 1/1 (frame 114/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 152.5ms
video 1/1 (frame 115/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 193.2ms
video 1/1 (frame 116/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 191.5ms
video 1/1 (frame 117/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 1 train, 189.5ms
video 1/1 (frame 118/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 bus, 1 truck, 192.9ms
video 1/1 (frame 119/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 211.3ms
video 1/1 (frame 120/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 195.1ms
video 1/1 (frame 121/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 truck, 190.3ms
video 1/1 (frame 122/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 2 trucks, 189.2ms
video 1/1 (frame 123/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 truck, 196.9ms
video 1/1 (frame 124/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 car, 2 trucks, 192.4ms
video 1/1 (frame 125/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 2 trucks, 187.9ms
video 1/1 (frame 126/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 190.3ms
video 1/1 (frame 127/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 2 trucks, 194.4ms
video 1/1 (frame 128/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 2 trucks, 185.7ms
video 1/1 (frame 129/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 2 trucks, 197.7ms
video 1/1 (frame 130/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 1 truck, 125.0ms
video 1/1 (frame 131/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 truck, 112.1ms
video 1/1 (frame 132/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 117.5ms
video 1/1 (frame 133/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 114.0ms
video 1/1 (frame 134/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 car, 113.0ms
video 1/1 (frame 135/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 bus, 114.8ms
video 1/1 (frame 136/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 10 cars, 1 bus, 129.3ms
video 1/1 (frame 137/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 11 cars, 116.6ms
video 1/1 (frame 138/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 118.9ms
video 1/1 (frame 139/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 8 cars, 117.9ms
video 1/1 (frame 140/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 persons, 3 cars, 113.1ms
video 1/1 (frame 141/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 118.4ms
video 1/1 (frame 142/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 115.3ms
video 1/1 (frame 143/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 1 truck, 136.0ms
video 1/1 (frame 144/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 8 cars, 115.9ms
video 1/1 (frame 145/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 116.8ms
video 1/1 (frame 146/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 4 cars, 112.7ms
video 1/1 (frame 147/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 115.6ms
video 1/1 (frame 148/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 112.9ms
video 1/1 (frame 149/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 115.0ms
video 1/1 (frame 150/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 112.8ms
video 1/1 (frame 151/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 133.2ms
video 1/1 (frame 152/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 115.3ms
video 1/1 (frame 153/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 1 truck, 117.4ms
video 1/1 (frame 154/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 116.6ms
video 1/1 (frame 155/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 117.0ms
video 1/1 (frame 156/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 120.3ms
video 1/1 (frame 157/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 3 cars, 119.3ms
video 1/1 (frame 158/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 car, 120.4ms
video 1/1 (frame 159/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 116.2ms
video 1/1 (frame 160/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 6 cars, 116.7ms
video 1/1 (frame 161/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 3 cars, 115.4ms
video 1/1 (frame 162/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 121.3ms
video 1/1 (frame 163/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 person, 3 cars, 116.2ms
video 1/1 (frame 164/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 6 cars, 112.6ms
video 1/1 (frame 165/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 119.4ms
video 1/1 (frame 166/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 130.8ms
video 1/1 (frame 167/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 113.7ms
video 1/1 (frame 168/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 114.9ms
video 1/1 (frame 169/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 1 car, 1 bus, 1 truck, 116.7ms
video 1/1 (frame 170/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 2 cars, 1 truck, 112.3ms
video 1/1 (frame 171/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 3 cars, 1 truck, 111.3ms
video 1/1 (frame 172/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 4 cars, 113.5ms
video 1/1 (frame 173/452) /content/WhatsApp Video 2026-10-06 at 00.27.03 (1).mp4: 384x640 5 cars, 124.7ms

In [ ]:
# ==========================================
# ASSIGNMENT 9 - FINAL RESULT & DOWNLOAD
# ==========================================

import os
import glob
import shutil
import pandas as pd
from collections import Counter
from google.colab import files

# Result folder
RESULT_DIR = "/content/results"
os.makedirs(RESULT_DIR, exist_ok=True)

# Count detected objects
counts = Counter()

for r in results:
    if r.boxes is not None and r.boxes.cls is not None:
        for cls_id in r.boxes.cls.cpu().numpy().astype(int):
            counts[model.names[cls_id]] += 1

# Create result table
summary = pd.DataFrame(
    [
        {"Object": obj, "Detections": count}
        for obj, count in counts.most_common()
    ]
)

print("========== OBJECT DETECTION RESULTS ==========")
display(summary)

# Save result table
csv_path = f"{RESULT_DIR}/detection_summary.csv"
summary.to_csv(csv_path, index=False)

# Find processed video
video_files = glob.glob("/content/cctv_detected/*")

for video in video_files:
    if video.lower().endswith((".mp4", ".avi", ".mov")):
        shutil.copy2(video, RESULT_DIR)
        print("Processed video copied:", video)
        break

# Create ZIP
zip_path = shutil.make_archive(
    "/content/Assignment_9_Results",
    "zip",
    RESULT_DIR
)

print("\n==========================================")
print("RESULTS CREATED SUCCESSFULLY")
print("==========================================")
print("CSV:", csv_path)
print("ZIP:", zip_path)

# Download ZIP
files.download(zip_path)

========== OBJECT DETECTION RESULTS ==========

   Object  Detections
0     car        2434
1   truck         234
2     bus          59
3  person          51
4   train           2

Processed video copied: /content/cctv_detected/WhatsApp Video 2026-10-06 at 00.27.03 (1).avi

==========================================
RESULTS CREATED SUCCESSFULLY
==========================================
CSV: /content/results/detection_summary.csv
ZIP: /content/Assignment_9_Results.zip

In [ ]:
# Final Result + Download Cell
# This cell is self-contained so it will not fail with NameError for pd/shutil/etc.

import os
import glob
import shutil
import pandas as pd
from collections import Counter

RESULT_DIR = "/content/results"
os.makedirs(RESULT_DIR, exist_ok=True)

# Make sure the YOLO model and detection results exist.
try:
    model
    results
except NameError:
    from ultralytics import YOLO
    if "VIDEO_PATH" not in globals():
        raise RuntimeError(
            "VIDEO_PATH is not defined. Run the video-upload cell first."
        )
    model = YOLO("yolo11n.pt")
    results = model.predict(
        source=VIDEO_PATH,
        save=True,
        project="/content",
        name="cctv_detected",
        conf=0.35,
        verbose=True
    )

# Count detected objects.
counts = Counter()

for r in results:
    if r.boxes is not None and r.boxes.cls is not None:
        for cls_id in r.boxes.cls.cpu().numpy().astype(int):
            counts[model.names[cls_id]] += 1

summary = pd.DataFrame(
    [{"Object": k, "Detections": v} for k, v in counts.most_common()],
    columns=["Object", "Detections"]
)

print("Object Detection Result")
display(summary)

summary.to_csv(f"{RESULT_DIR}/detection_summary.csv", index=False)

# Copy processed video to result folder.
output_dir = "/content/cctv_detected"
videos = glob.glob(output_dir + "/*")

copied_video = False
for v in videos:
    if v.lower().endswith((".mp4", ".avi", ".mov")):
        shutil.copy2(v, RESULT_DIR)
        print("Processed video copied:", os.path.basename(v))
        copied_video = True
        break

if not copied_video:
    print("Processed video was not found in /content/cctv_detected.")
    print("Check the folder in the Colab Files panel.")

# Create ZIP.
zip_file = shutil.make_archive(
    "/content/Assignment_9_Results",
    "zip",
    RESULT_DIR
)

print("Created:", zip_file)

# Download ZIP.
from google.colab import files
files.download(zip_file)

Object Detection Result

   Object  Detections
0     car        2434
1   truck         234
2     bus          59
3  person          51
4   train           2

Processed video copied: WhatsApp Video 2026-10-06 at 00.27.03 (1).avi
Created: /content/Assignment_9_Results.zip